# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Dimon/Stepic/httpserver/server_final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Dimon/Stepic/httpserver/server_final/tmp

# Include any dependencies generated for this target.
include CMakeFiles/../release/hserv.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/../release/hserv.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/../release/hserv.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../release/hserv.dir/flags.make

CMakeFiles/../release/hserv.dir/src/main.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/main.cpp.o: ../src/main.cpp
CMakeFiles/../release/hserv.dir/src/main.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/../release/hserv.dir/src/main.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/main.cpp.o -MF CMakeFiles/../release/hserv.dir/src/main.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/main.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/main.cpp

CMakeFiles/../release/hserv.dir/src/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/main.cpp > CMakeFiles/../release/hserv.dir/src/main.cpp.i

CMakeFiles/../release/hserv.dir/src/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/main.cpp -o CMakeFiles/../release/hserv.dir/src/main.cpp.s

CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o: ../src/lib/daemonizator.cpp
CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o -MF CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/lib/daemonizator.cpp

CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/lib/daemonizator.cpp > CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.i

CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/lib/daemonizator.cpp -o CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.s

CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o: ../src/lib/errorproc.cpp
CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o -MF CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/lib/errorproc.cpp

CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/lib/errorproc.cpp > CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.i

CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/lib/errorproc.cpp -o CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.s

CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o: ../src/lib/unblock.cpp
CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o -MF CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/lib/unblock.cpp

CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/lib/unblock.cpp > CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.i

CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/lib/unblock.cpp -o CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.s

CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o: ../src/lib/worker.cpp
CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o -MF CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/lib/worker.cpp

CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/lib/worker.cpp > CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.i

CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/lib/worker.cpp -o CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.s

CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o: ../src/lib/fdtransceiver.cpp
CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o -MF CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/lib/fdtransceiver.cpp

CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/lib/fdtransceiver.cpp > CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.i

CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/lib/fdtransceiver.cpp -o CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.s

CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o: CMakeFiles/../release/hserv.dir/flags.make
CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o: ../src/lib/webproc.cpp
CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o: CMakeFiles/../release/hserv.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o -MF CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o.d -o CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o -c /home/Dimon/Stepic/httpserver/server_final/src/lib/webproc.cpp

CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/Dimon/Stepic/httpserver/server_final/src/lib/webproc.cpp > CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.i

CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/Dimon/Stepic/httpserver/server_final/src/lib/webproc.cpp -o CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.s

# Object files for target ../release/hserv
__/release/hserv_OBJECTS = \
"CMakeFiles/../release/hserv.dir/src/main.cpp.o" \
"CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o" \
"CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o" \
"CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o" \
"CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o" \
"CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o" \
"CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o"

# External object files for target ../release/hserv
__/release/hserv_EXTERNAL_OBJECTS =

../release/hserv: CMakeFiles/../release/hserv.dir/src/main.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/src/lib/daemonizator.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/src/lib/errorproc.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/src/lib/unblock.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/src/lib/worker.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/src/lib/fdtransceiver.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/src/lib/webproc.cpp.o
../release/hserv: CMakeFiles/../release/hserv.dir/build.make
../release/hserv: CMakeFiles/../release/hserv.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/Dimon/Stepic/httpserver/server_final/tmp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Linking CXX executable ../release/hserv"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../release/hserv.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../release/hserv.dir/build: ../release/hserv
.PHONY : CMakeFiles/../release/hserv.dir/build

CMakeFiles/../release/hserv.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../release/hserv.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../release/hserv.dir/clean

CMakeFiles/../release/hserv.dir/depend:
	cd /home/Dimon/Stepic/httpserver/server_final/tmp && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/Dimon/Stepic/httpserver/server_final /home/Dimon/Stepic/httpserver/server_final /home/Dimon/Stepic/httpserver/server_final/tmp /home/Dimon/Stepic/httpserver/server_final/tmp /home/Dimon/Stepic/httpserver/server_final/tmp/release/hserv.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../release/hserv.dir/depend

